window.factorConfig = {
  Anxiety: {
    type: "range",
    description: "THis is a small description about this important test.",
    info: "This is an info",
    label: "Score of Anxiety",
    min: 0,
    max: 3,
    value: 1,
  },
  Apathy: {
    type: "range",
    label: "Score of Apathy",
    min: 0,
    max: 2,
    value: 1,
  },
  Benton: {
    type: "range",
    label: "Score of Benton",
    min: 5.1,
    max: 16.38,
    value: 10,
  },
  Clock: {
    type: "range",
    label: "Score of Clock",
    min: 1,
    max: 7,
    value: 4,
  },
  Cognition: {
    type: "range",
    label: "Score of Cognition",
    min: 0,
    max: 2,
    value: 1,
  },
  COGSTATE: {
    type: "range",
    label: "Score of COGSTATE",
    min: 1,
    max: 2,
    value: 1,
    step: 1,
  },
  Constipate: {
    type: "range",
    label: "Score of Constipate",
    min: 0,
    max: 3,
    value: 1,
  },
  Depress: {
    type: "range",
    label: "Score of Depress",
    min: 0,
    max: 4,
    value: 1,
  },
  DopaDefic: {
    type: "range",
    label: "Score of DopaDefic",
    min: 0,
    max: 2,
    value: 1,
  },
  Education: {
    type: "range",
    label: "Score of Education",
    min: 8,
    max: 26,
    value: 12,
  },
  Epworth: {
    type: "range",
    label: "Score of Epworth",
    min: 0,
    max: 11,
    value: 5,
  },
  Fatigue: {
    type: "range",
    label: "Score of Fatigue",
    min: 0,
    max: 4,
    value: 2,
  },
  Geriatric_Depression: {
    type: "range",
    label: "Score of Geriatric_Depression",
    min: 1,
    max: 15,
    value: 6,
  },
  Hallucination: {
    type: "range",
    label: "Score of Hallucination",
    min: 0,
    max: 1,
    value: 0,
    step: 1,
  },
  Hand: {
    type: "range",
    label: "Score of Hand",
    min: 1,
    max: 3,
    value: 1,
  },
  Hopkins: {
    type: "range",
    label: "Score of Hopkins",
    min: 20,
    max: 64,
    value: 30,
  },
  Hopkins_Recog: {
    type: "range",
    label: "Score of Hopkins_Recog",
    min: 20,
    max: 61,
    value: 30,
  },
  Impulsive_CompulsiveBehavior: {
    type: "range",
    label: "Score of Impulsive_CompulsiveBehavior",
    min: 0,
    max: 1,
    value: 1,
    step: 1,
  },
  Impulsive_ICD: {
    type: "range",
    label: "Score of Impulsive_ICD",
    min: 0,
    max: 4,
    value: 0,
  },
  LetterNumber: {
    type: "range",
    label: "Score of LetterNumber",
    min: 4,
    max: 19,
    value: 10,
  },
  Lexical_Fluency: {
    type: "range",
    label: "Score of Lexical_Fluency",
    min: 11,
    max: 101,
    value: 50,
  },
  LightHead: {
    type: "range",
    label: "Score of LightHead",
    min: 0,
    max: 3,
    value: 1,
  },
  Modif_Boston: {
    type: "range",
    label: "Score of Modif_Boston",
    min: 8,
    max: 60,
    value: 30,
  },
  Montreal_Cognitive: {
    type: "range",
    label: "Score of Montreal_Cognitive",
    min: 17,
    max: 30,
    value: 20,
  },
  Pain: {
    type: "range",
    label: "Score of Pain",
    min: 0,
    max: 3,
    value: 1,
  },
  REM_AwakeDream: {
    type: "range",
    label: "Score of REM_AwakeDream",
    min: 0,
    max: 1,
    value: 0,
    step: 1,
  },
  REM_AwakeProblem: {
    type: "range",
    label: "Score of REM_AwakeProblem",
    min: 0,
    max: 2,
    value: 1,
  },
  REM_Dream: {
    type: "range",
    label: "Score of REM_Dream",
    min: 0,
    max: 3,
    value: 1,
  },
  REM_Movement: {
    type: "range",
    label: "Score of REM_Movement",
    min: 0,
    max: 6,
    value: 1,
  },
  SCOPA_Cardio: {
    type: "range",
    label: "Score of SCOPA_Cardio",
    min: 0,
    max: 6,
    value: 1,
  },
  SCOPA_Eye: {
    type: "range",
    label: "Score of SCOPA_Eye",
    min: 0,
    max: 3,
    value: 1,
  },
  SCOPA_Gastro: {
    type: "range",
    label: "Score of SCOPA_Gastro",
    min: 0,
    max: 9,
    value: 1,
  },
  SCOPA_Sex: {
    type: "range",
    label: "Score of SCOPA_Sex",
    min: 0,
    max: 6,
    value: 1,
  },
  SCOPA_Thermo: {
    type: "range",
    label: "Score of SCOPA_Thermo",
    min: 0,
    max: 6,
    value: 1,
  },
  SCOPA_Urine: {
    type: "range",
    label: "Score of SCOPA_Urine",
    min: 0,
    max: 17,
    value: 1,
  },
  Semantic: {
    type: "range",
    label: "Score of Semantic",
    min: 25,
    max: 81,
    value: 60,
  },
  SleepDay: {
    type: "range",
    label: "Score of SleepDay",
    min: 0,
    max: 2,
    value: 1,
  },
  SleepNight: {
    type: "range",
    label: "Score of SleepNight",
    min: 0,
    max: 4,
    value: 1,
  },
  STAIA: {
    type: "range",
    label: "Score of STAIA",
    min: 31,
    max: 54,
    value: 40,
  },
  STAIS: {
    type: "range",
    label: "Score of STAIS",
    min: 19,
    max: 59,
    value: 40,
  },
  Symbol_Digit: {
    type: "range",
    label: "Score of Symbol_Digit",
    min: 20,
    max: 80,
    value: 60,
  },
  Trail_Making_A: {
    type: "range",
    label: "Score of Trail_Making_A",
    min: 13,
    max: 150,
    value: 100,
  },
  Trail_Making_B: {
    type: "range",
    label: "Score of Trail_Making_B",
    min: 20,
    max: 294,
    value: 100,
  },
  UPSIT: {
    type: "range",
    label: "Score of UPSIT",
    min: 0,
    max: 40,
    value: 30,
  },
  Urine: {
    type: "range",
    label: "Score of Urine",
    min: 0,
    max: 4,
    value: 2,
  },
};

console.log("factorConfig loaded");
